pipeline {
    agent any

    tools {
        maven 'maven'
    }


    stages {
        stage('Checkout') {
            steps {
                // Assuming the code is already checked out, or add git checkout if needed
                echo 'Code checked out'
            }
        }

        stage('Build') {
            steps {
                dir('selenium tests') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {

                dir('selenium tests') {
                    bat 'mvn test'
                }
              
            }
        }

        stage('Publish Results') {
            steps {
                dir('selenium tests') {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/surefire-reports/*.html', allowEmptyArchive: true
        }
    }
}
